-- تشغيلة 1/3: الجداول (schema)
create extension if not exists pgcrypto;
 alter database postgres set timezone to 'Africa/Cairo';
 create table public.profiles ( id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', phone text, parent_phone text, grade text not null default 'first_secondary' check (grade in ('first_secondary', 'second_secondary')), role text not null default 'student' check (role in ('student', 'admin')), email text, created_at timestamptz not null default now() );
 comment on table public.profiles is 'بيانات الطلاب والأدمن — بترتبط بجدول المستخدمين في auth';
 create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' );
 $$;
 create or replace function public.is_student() returns boolean language sql stable security definer set search_path = public as $$ select exists ( select 1 from public.profiles where id = auth.uid() and role = 'student' );
 $$;
 create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, phone, parent_phone, grade, email) values ( new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), nullif(new.raw_user_meta_data->>'phone', ''), nullif(new.raw_user_meta_data->>'parent_phone', ''), coalesce(new.raw_user_meta_data->>'grade', 'first_secondary'), new.email ) on conflict (id) do update set email = excluded.email, full_name = case when public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end;
 return new;
 end;
 $$;
 drop trigger if exists on_auth_user_created on auth.users;
 create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
 create or replace function public.prevent_profile_escalation() returns trigger language plpgsql security definer set search_path = public as $$ begin if not public.is_admin() and (new.role is distinct from old.role or new.grade is distinct from old.grade) then raise exception 'غير مسموح بتغيير الصلاحية أو الصف الدراسي';
 end if;
 return new;
 end;
 $$;
 drop trigger if exists profiles_role_guard on public.profiles;
 create trigger profiles_role_guard before update on public.profiles for each row execute procedure public.prevent_profile_escalation();
 create table public.courses ( id uuid primary key default gen_random_uuid(), title text not null, description text, grade text not null check (grade in ('first_secondary', 'second_secondary')), video_url text, order_index int not null default 1, created_at timestamptz not null default now() );
 create view public.courses_public with (security_invoker = on) as select id, title, description, grade, order_index from public.courses;
 create table public.exams ( id uuid primary key default gen_random_uuid(), title text not null, description text, grade text not null check (grade in ('first_secondary', 'second_secondary')), duration_minutes int, start_at timestamptz, end_at timestamptz, is_published boolean not null default false, created_at timestamptz not null default now() );
 create table public.exam_questions ( id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id) on delete cascade, question_text text not null, type text not null check (type in ('mcq', 'true_false', 'short_answer')), options jsonb, correct_answer text, points int not null default 1, order_index int not null default 1 );
 create index exam_questions_exam_idx on public.exam_questions (exam_id, order_index);
 create table public.exam_submissions ( id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.profiles(id) on delete cascade, answers jsonb not null default '{}'::jsonb, auto_score numeric default 0, manual_score numeric default 0, score numeric, grade_released boolean not null default false, submitted_at timestamptz not null default now(), unique (exam_id, student_id) );
 create index exam_submissions_exam_idx on public.exam_submissions (exam_id);
 create index exam_submissions_student_idx on public.exam_submissions (student_id);
 create table public.bookings ( id uuid primary key default gen_random_uuid(), student_id uuid not null references public.profiles(id) on delete cascade, requested_datetime timestamptz not null, subject text not null default 'cs', status text not null default 'pending' check (status in ('pending', 'confirmed', 'rejected')), notes text, created_at timestamptz not null default now() );
 create index bookings_student_idx on public.bookings (student_id);
 create index bookings_status_idx on public.bookings (status);
 create table public.competitions ( id uuid primary key default gen_random_uuid(), title text not null, description text, grade text not null check (grade in ('first_secondary', 'second_secondary')), deadline timestamptz, details text, created_at timestamptz not null default now() );
 create index competitions_grade_idx on public.competitions (grade);
 create table public.notifications ( id uuid primary key default gen_random_uuid(), student_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text, is_read boolean not null default false, created_at timestamptz not null default now() );
 create index notifications_student_idx on public.notifications (student_id, created_at desc);
 create table public.contact_links ( id uuid primary key default gen_random_uuid(), platform text not null, label text, value text not null );
 create unique index contact_links_platform_idx on public.contact_links (platform);
