import { useParams, Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { useCourse } from '../../hooks/useCourses.js';
import { useAuth } from '../../hooks/useAuth.js';
import Card from '../../components/ui/Card.jsx';
import Button from '../../components/ui/Button.jsx';
import Badge from '../../components/ui/Badge.jsx';
import Icon from '../../components/ui/Icon.jsx';
import Input from '../../components/ui/Input.jsx';
import Textarea from '../../components/ui/Textarea.jsx';
import Skeleton from '../../components/ui/Skeleton.jsx';
import SubscriptionGate from '../../components/academy/SubscriptionGate.jsx';
import { supabase } from '../../lib/supabaseClient.js';
import { fetchCourseHomeworks, fetchCourseFiles, fetchCourseComments, addCourseComment, deleteCourseComment, uploadCourseFile, addCourseFile, deleteCourseFile } from '../../services/courseService.js';
import { createBooking } from '../../services/bookingService.js';
import { useToast } from '../../components/ui/Toast.jsx';
import { GRADE_SHORT } from '../../config/site.js';
import { getFriendlyError } from '../../utils/errors.js';
import { formatDateTime } from '../../utils/formatDate.js';
import { fetchPaymentMethods } from '../../services/paymentService.js';

export default function CourseDetails() {
  const { courseId } = useParams();
  const { profile } = useAuth();
  const { course, loading } = useCourse(courseId, profile?.grade);
  const toast = useToast();
  const [lessons, setLessons] = useState([]);
  const [homeworks, setHomeworks] = useState([]);
  const [files, setFiles] = useState([]);
  const [comments, setComments] = useState([]);
  const [extraLoading, setExtraLoading] = useState(true);
  const [canAccess, setCanAccess] = useState(false);
  const [commentBody, setCommentBody] = useState('');
  const [commentSubmitting, setCommentSubmitting] = useState(false);
  const [uploadTitle, setUploadTitle] = useState('');
  const [uploadFile, setUploadFile] = useState(null);
  const [uploadSubmitting, setUploadSubmitting] = useState(false);
  const [showSubscribe, setShowSubscribe] = useState(false);
  const [subForm, setSubForm] = useState({ parent_phone: '', transfer_number: '' });
  const [submittingSub, setSubmittingSub] = useState(false);
  const [payMethods, setPayMethods] = useState([]);
  useEffect(() => { fetchPaymentMethods().then(({ data }) => setPayMethods(data || [])); }, []);
  useEffect(() => {
    if (!courseId) return;
    setExtraLoading(true);
    Promise.all([supabase.rpc('get_course_lessons', { p_course_id: courseId }), fetchCourseHomeworks(courseId), fetchCourseFiles(courseId), fetchCourseComments(courseId)]).then(([l, h, f, c]) => {
      setLessons(Array.isArray(l.data) ? l.data : []); setHomeworks(Array.isArray(h.data) ? h.data : []); setFiles(Array.isArray(f.data) ? f.data : []); setComments(Array.isArray(c.data) ? c.data : []); setCanAccess(course?.accessible ?? false); setExtraLoading(false);
    }).catch(() => setExtraLoading(false));
  }, [courseId]);
  if (loading) return <div className="space-y-4"><Skeleton className="h-10 w-64" /><Skeleton className="h-72" /></div>;
  if (!course) return <Card className="flex flex-col items-center gap-4 py-14 text-center"><p className="text-muted">الكورس ده مش موجود.</p><Link to="/student/courses"><Button variant="secondary">رجوع للكورسات</Button></Link></Card>;
  const isProfessional = course.grade === 'professional';
  const isMyGrade = profile?.grade === course.grade;
  const effectiveAccess = course?.accessible ?? false;
  const canWatch = Boolean(profile) && effectiveAccess && (isProfessional || isMyGrade);
  const gradeLabel = GRADE_SHORT[course.grade] || course.grade;
  const submitComment = async (e) => { e.preventDefault(); if (!commentBody.trim()) return toast.error('اكتب تعليقك الأول'); setCommentSubmitting(true); const { error } = await supabase.rpc('add_course_comment', { p_course_id: courseId, p_body: commentBody }); setCommentSubmitting(false); if (error) return toast.error(getFriendlyError(error, 'فشل إضافة التعليق')); setCommentBody(''); toast.success('تمت إضافة تعليقك'); const { data } = await fetchCourseComments(courseId); setComments(data || []); };
  const removeMyComment = async (commentId) => { if (!window.confirm('حذف تعليقك؟')) return; const { error } = await deleteCourseComment(commentId); if (error) return toast.error(getFriendlyError(error, 'فشل الحذف')); toast.success('تم الحذف'); const { data } = await fetchCourseComments(courseId); setComments(data || []); };
  const submitUpload = async (e) => { e.preventDefault(); if (!uploadTitle.trim()) return toast.error('اكتب اسم الملف'); if (!uploadFile) return toast.error('اختار ملف PDF أو ZIP الأول'); setUploadSubmitting(true); const { data: upload, error: upErr } = await uploadCourseFile(uploadFile, { courseId, studentId: profile?.id }); if (upErr) { setUploadSubmitting(false); return toast.error(getFriendlyError(upErr, 'فشل رفع الملف')); } const { error } = await addCourseFile(courseId, { title: uploadTitle.trim(), fileUrl: upload.fileUrl, fileType: upload.fileType }); setUploadSubmitting(false); if (error) return toast.error(getFriendlyError(error, 'فشل الحفظ')); toast.success('تم رفع ملفك'); setUploadTitle(''); setUploadFile(null); const { data } = await fetchCourseFiles(courseId); setFiles(data || []); };
  const removeFile = async (fileId) => { if (!window.confirm('حذف هذا الملف؟')) return; const { error } = await deleteCourseFile(fileId); if (error) return toast.error(getFriendlyError(error, 'فشل الحذف')); toast.success('تم الحذف'); const { data } = await fetchCourseFiles(courseId); setFiles(data || []); };
  const submitSubscription = async (e) => { e.preventDefault(); if (!subForm.transfer_number.trim()) return toast.error('اكتب الرقم اللي حولت منه'); setSubmittingSub(true); const { error } = await createBooking({ studentId: profile.id, fullName: profile.full_name, phone: profile.phone, parentPhone: subForm.parent_phone, grade: 'professional', month: null, courseId, notes: `اشتراك في الكورس الاحترافي: ${course.title}`, transferNumber: subForm.transfer_number.trim() }); setSubmittingSub(false); if (error) return toast.error(getFriendlyError(error, 'فشل إرسال طلب الاشتراك')); toast.success('تم إرسال طلب اشتراكك — قيد مراجعة المستر، وكمل الخطوات اللي تحت'); };
  return (<SubscriptionGate><div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-stream">#{String(course.order_index || 1).padStart(2, '0')} — {gradeLabel}</p><h1 className="mt-1 font-display text-2xl font-black">{course.title}</h1>{isProfessional && course.price != null && <p className="mt-1 text-sm font-bold text-signal">💰 سعر الكورس: {course.price} جنيه</p>}</div><Link to="/student/courses"><Button variant="secondary" size="sm"><Icon name="chevronRight" className="h-4 w-4" /> كل الكورسات</Button></Link></div>{!effectiveAccess ? (<Card className="space-y-4 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-black">اشترك في {course.title}</h2><p className="mt-1 text-sm text-muted">{course.description || 'كورس بنظام مستويات — اشترك علشان يفتح ليك.'}</p></div><div className="text-center"><p className="font-display text-3xl font-black text-signal">{course.price ?? '—'} <span className="text-base font-bold text-muted">جنيه</span></p>{!showSubscribe && <Button className="mt-2" onClick={() => setShowSubscribe(true)}><Icon name="lock" className="h-4 w-4" /> اشترك</Button>}</div></div>{showSubscribe && (<div className="space-y-4 rounded-lens border border-signal/40 bg-signal/10 p-4"><h3 className="font-display text-base font-black text-paper">خطوات الاشتراك</h3><ul className="space-y-1.5 text-sm leading-relaxed text-paper/90">{payMethods.length ? payMethods.map((m) => <li key={m.id}>{m.name}: <b dir="ltr" className="font-mono">{m.details}</b></li>) : <li>حوّل <b>{course.price ?? '—'} جنيه</b></li>}</ul><form onSubmit={submitSubscription} className="grid gap-3 sm:grid-cols-2"><Input name="parent_phone" label="موبايل ولي الأمر (اختياري)" dir="ltr" placeholder="01xxxxxxxxx" value={subForm.parent_phone} onChange={(e) => setSubForm({ ...subForm, parent_phone: e.target.value })} /><Input name="transfer_number" label="الرقم اللي حولت منه *" dir="ltr" placeholder="01xxxxxxxxx" value={subForm.transfer_number} onChange={(e) => setSubForm({ ...subForm, transfer_number: e.target.value })} required /><div className="sm:col-span-2"><Button type="submit" loading={submittingSub} className="w-full">إرسال طلب الاشتراك</Button></div></form></div>)}</Card>) : (<><Card className="overflow-hidden"><div className="flex items-center gap-2 border-b border-ink-600 px-4 py-3"><Icon name="layers" className="h-5 w-5 text-signal" /><p className="font-display text-sm font-bold text-paper">اختر درسًا للبدء</p><span className="ms-auto rounded-full bg-ink-800 px-2 py-0.5 font-mono text-xs text-muted">{lessons.length} درس</span></div>{extraLoading ? <div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3"><Skeleton className="h-32" /><Skeleton className="h-32" /><Skeleton className="h-32" /></div> : lessons.length===0 ? <p className="p-8 text-center text-sm text-muted">لا توجد دروس بعد — تابعنا قريبًا.</p> : <div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.map((lesson) => { const accessible = lesson.accessible || lesson.is_free; return (<div key={lesson.lesson_id} className={`flex flex-col rounded-lens border p-4 ${accessible ? 'border-ink-600 bg-ink-900 hover:border-signal/40' : 'border-ink-700 bg-ink-800/40 opacity-85'}`}><div className="flex items-start justify-between gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-ink-700 font-mono text-xs font-bold text-paper">{String(lesson.order_index).padStart(2, '0')}</span><div className="flex gap-1">{lesson.is_free && <Badge color="success">مجاني</Badge>}{!accessible && <Badge color="warning">مقفول</Badge>}{accessible && !lesson.is_free && <Badge color="stream">متاح</Badge>}</div></div><h3 className="mt-3 font-display text-sm font-black text-paper line-clamp-2">{lesson.title}</h3>{lesson.description && <p className="mt-1 line-clamp-2 text-xs text-muted">{lesson.description}</p>}<div className="mt-4">{accessible ? <Link to={`/student/courses/${courseId}/lesson/${lesson.lesson_id}`}><Button size="sm" className="w-full"><Icon name="play" className="h-4 w-4" /> شاهد الدرس</Button></Link> : <Button size="sm" variant="secondary" className="w-full" onClick={() => toast.info('هذا الدرس للمشتركين — اشترك من صفحة الحجوزات')}><Icon name="lock" className="h-4 w-4" /> مقفول</Button>}</div></div>);})}</div>}</Card></>)}</div></SubscriptionGate>);
}
